version: "3"

vars:
  DOTFILES_DIR: "{{.USER_WORKING_DIR}}"
  HOME_DIR: "{{.HOME}}"

tasks:
  cp-zshrc:
    desc: Copy ZSH configuration to home directory (for work laptop)
    cmds:
      - cp {{.DOTFILES_DIR}}/home/.zshrc {{.HOME_DIR}}/.zshrc
    status:
      - test "$(readlink {{.HOME_DIR}}/.zshrc)" = "{{.DOTFILES_DIR}}/home/.zshrc"

  ln-wezterm:
    desc: Symlink WezTerm configuration
    cmds:
      - mkdir -p {{.HOME_DIR}}/.config
      - ln -svf {{.DOTFILES_DIR}}/home/.config/wezterm {{.HOME_DIR}}/.config/wezterm
    status:
      - test "$(readlink {{.HOME_DIR}}/.config/wezterm)" = "{{.DOTFILES_DIR}}/home/.config/wezterm"

  ln-nvim:
    desc: Symlink Neovim configuration
    cmds:
      - mkdir -p {{.HOME_DIR}}/.config
      - ln -svf {{.DOTFILES_DIR}}/home/.config/nvim {{.HOME_DIR}}/.config/nvim
    status:
      - test "$(readlink {{.HOME_DIR}}/.config/nvim)" = "{{.DOTFILES_DIR}}/home/.config/nvim"

  ln-zshrc:
    desc: Symlink ZSH configuration
    cmds:
      - ln -svf {{.DOTFILES_DIR}}/home/.zshrc {{.HOME_DIR}}/.zshrc
    status:
      - test "$(readlink {{.HOME_DIR}}/.zshrc)" = "{{.DOTFILES_DIR}}/home/.zshrc"

  ln-ideavimrc:
    desc: Symlink ideavim configuration (InteliJ Vim mode)
    cmds:
      - ln -svf {{.DOTFILES_DIR}}/home/.ideavimrc {{.HOME_DIR}}/.ideavimrc
    status:
      - test "$(readlink {{.HOME_DIR}}/.ideavimrc)" = "{{.DOTFILES_DIR}}/home/.ideavimrc"

  ln-zellij:
    desc: Symlink Zellij configuration
    cmds:
      - ln -svf {{.DOTFILES_DIR}}/home/.config/zellij {{.HOME_DIR}}/.config/zellij
    status:
      - test "$(readlink {{.HOME_DIR}}/.config/zellij)" = "{{.DOTFILES_DIR}}/home/.config/zellij"

  ln-ghostty:
    desc: Symlink Ghostty configuration
    cmds:
      - ln -svf {{.DOTFILES_DIR}}/home/.config/ghostty {{.HOME_DIR}}/.config/ghostty
    status:
      - test "$(readlink {{.HOME_DIR}}/.config/ghostty)" = "{{.DOTFILES_DIR}}/home/.config/ghostty"

  ln-zed:
    desc: Symlink Zed configuration files
    cmds:
      - ln -svf {{.DOTFILES_DIR}}/home/.config/zed/settings.json {{.HOME_DIR}}/.config/zed/settings.json
      - ln -svf {{.DOTFILES_DIR}}/home/.config/zed/keymap.json {{.HOME_DIR}}/.config/zed/keymap.json
    status:
      - test "$(readlink {{.HOME_DIR}}/.config/zed)" = "{{.DOTFILES_DIR}}/home/.config/zed"

  ln-opencode:
    desc: Symlink OpenCode configuration files
    cmds:
      - test -e {{.DOTFILES_DIR}}/home/.config/opencode/AGENTS.md && ln -svf {{.DOTFILES_DIR}}/home/.config/opencode/AGENTS.md {{.HOME_DIR}}/.config/opencode/AGENTS.md || true
      - test -e {{.DOTFILES_DIR}}/home/.config/opencode/agent && ln -svf {{.DOTFILES_DIR}}/home/.config/opencode/agent {{.HOME_DIR}}/.config/opencode/agent || true
      - test -e {{.DOTFILES_DIR}}/home/.config/opencode/skill && ln -svf {{.DOTFILES_DIR}}/home/.config/opencode/skill {{.HOME_DIR}}/.config/opencode/skill || true
      - test -e {{.DOTFILES_DIR}}/home/.config/opencode/command && ln -svf {{.DOTFILES_DIR}}/home/.config/opencode/command {{.HOME_DIR}}/.config/opencode/command || true

  ln-claude-code:
    desc: Symlink Claude Code configuration files
    cmds:
      - test -e {{.DOTFILES_DIR}}/home/.claude/agents && ln -svf {{.DOTFILES_DIR}}/home/.claude/agents {{.HOME_DIR}}/.claude/agents || true
      - test -e {{.DOTFILES_DIR}}/home/.claude/commands && ln -svf {{.DOTFILES_DIR}}/home/.claude/commands {{.HOME_DIR}}/.claude/commands || true
      - test -e {{.DOTFILES_DIR}}/home/.claude/skills && ln -svf {{.DOTFILES_DIR}}/home/.claude/skills {{.HOME_DIR}}/.claude/skills || true
      - test -e {{.DOTFILES_DIR}}/home/.claude/settings.json && ln -svf {{.DOTFILES_DIR}}/home/.claude/settings.json {{.HOME_DIR}}/.claude/settings.json || true
      - test -e {{.DOTFILES_DIR}}/home/.claude/statusline-command.sh && ln -svf {{.DOTFILES_DIR}}/home/.claude/statusline-command.sh {{.HOME_DIR}}/.claude/statusline-command.sh || true

  ln-all:
    desc: Symlink all configurations defined in this Taskfile
    deps:
      - ln-wezterm
      - ln-nvim
      - ln-zshrc
      - ln-ideavimrc
      - ln-zellij
      - ln-ghostty

  zsh-plugins:
    desc: Pull ZSH plugins from brew
    cmds:
      - brew install zsh-autosuggestions
      - brew install zsh-syntax-highlighting

  default:
    desc: List all available tasks by default
    cmds:
      - task --list
    silent: true
