[window]
dimensions = { columns = 150, lines = 45}
decorations = "Full"
padding = {x = 5, y = 5}
dynamic_title = false

[font]
size = 12
normal = { family = "JetbrainsMono Nerd Font"}

[shell]
program = 'C:\Windows\System32\wsl.exe'
args = ["--cd ~"]

[cursor]
style = "Beam"
vi_mode_style = { shape = "Block", blinking = "Off" }

# Colour scheme CarbonFox
[colors.primary]
background = '#161616'
foreground = '#f2f4f8'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#ee5396'
green   = '#25be6a'
yellow  = '#08bdba'
blue    = '#78a9ff'
magenta = '#be95ff'
cyan    = '#33b1ff'
white   = '#dfdfe0'

# Bright colors
[colors.bright]
black   = '#484848'
red     = '#f16da6'
green   = '#46c880'
yellow  = '#2dc7c4'
blue    = '#8cb6ff'
magenta = '#c8a5ff'
cyan    = '#52bdff'
white   = '#e4e4e5'
